# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:13:52+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from pydantic import constr

from models import (
    AssetRenderResponse,
    AssetResponse,
    Edit,
    QueuedResponse,
    RenderResponse,
)

app = MCPProxy(
    description="Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.\n\nYou arrange and configure an edit and POST it to the API which will render your media and provide a file  location when complete.\n\nFor more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.gitbook.io/docs/guides/getting-started) documentation.\nThere are two main API's, one for editing and generating assets (Edit API) and one for managing hosted assets (Serve API).\n\nThe Edit API base URL is: <b>https://api.shotstack.io/{version}</b>\n\nThe Serve API base URL is: <b>https://api.shotstack.io/serve/{version}</b>",
    title='Shotstack',
    version='v1',
    servers=[
        {
            'url': 'https://api.shotstack.io/{version}',
            'variables': {
                'version': {
                    'default': 'v1',
                    'description': 'Set the stage to `v1` for production usage without watermarks. Set to `stage` to use the development sandbox.',
                    'enum': ['v1', 'stage'],
                }
            },
        },
        {
            'url': 'https://api.shotstack.io/serve/{version}',
            'variables': {
                'version': {
                    'default': 'v1',
                    'description': 'Set the stage to `v1` for production usage. Set to `stage` to use the development sandbox.',
                    'enum': ['v1', 'stage'],
                }
            },
        },
    ],
)


@app.get(
    '/assets/render/{id}',
    description=""" A render may generate more than one file, such as a video, thumbnail and poster image. When the assets are created the only known id is the render id returned by the original [render request](#render-video), status  request or webhook. This endpoint lets you look up one or more assets by the render id.

**base URL:** https://api.shotstack.io/serve/{version} """,
    tags=['asset_operations', 'render_process_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_asset_by_render_id(
    id: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ),
):
    """
    Get Asset by Render ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/assets/{id}',
    description=""" Delete an asset by its asset id. If a render creates multiple assets, such as thumbnail and poster images, each asset must be deleted individually by the asset id.

**base URL:** https://api.shotstack.io/serve/{version} """,
    tags=['asset_operations'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def delete_asset(
    id: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ),
):
    """
    Delete Asset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/assets/{id}',
    description=""" The Serve API is used to interact with, and delete hosted assets including videos, images, audio files,  thumbnails and poster images. Use this endpoint to fetch an asset by asset id. Note that an asset id is unique for each asset and different from the render id.

**base URL:** https://api.shotstack.io/serve/{version} """,
    tags=['asset_operations'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_asset(
    id: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ),
):
    """
    Get Asset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/render',
    description=""" Queue and render the contents of a timeline as a video, image or audio file. """,
    tags=['asset_operations', 'render_process_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def post_render(body: Edit):
    """
    Render Asset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/render/{id}',
    description=""" Get the rendering status, temporary asset url and details of a render by ID.

**base URL:** https://api.shotstack.io/{version} """,
    tags=['render_process_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_render(
    id: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ),
):
    """
    Get Render Status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
