# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:13:52+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, confloat, conint


class Status(Enum):
    importing = 'importing'
    ready = 'ready'
    failed = 'failed'
    deleted = 'deleted'


class AssetResponseAttributes(BaseModel):
    created: Optional[str] = Field(
        None,
        description='The time the asset was created.',
        examples=['2021-06-30T09:42:29.446Z'],
    )
    filename: Optional[str] = Field(
        None,
        description='The asset file name.',
        examples=['2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7.mp4'],
    )
    id: Optional[str] = Field(
        None,
        description='The unique id of the hosted asset in UUID format.',
        examples=['a4482cbf-e321-42a2-ac8b-947d26886840'],
    )
    owner: Optional[str] = Field(
        None, description='The owner id of the render task.', examples=['5ca6hu7s9k']
    )
    region: Optional[str] = Field(
        None,
        description='The region the asset is hosted, currently only `au` (Australia).',
        examples=['au'],
    )
    renderId: Optional[str] = Field(
        None,
        description='The original render id that created the asset in UUID format. Multiple assets can share the same render id.',
        examples=['2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7'],
    )
    status: Optional[Status] = Field(
        None,
        description='The status of the asset. <ul>\n  <li>`importing` - the asset is being copied to the hosting service</li>\n  <li>`ready` - the asset is ready to be served to users</li>\n  <li>`failed` - the asset failed to copy or delete</li>\n  <li>`deleted` - the asset has been deleted</li>\n</ul>',
        examples=['ready'],
    )
    updated: Optional[str] = Field(
        None,
        description='The time the asset status was last updated.',
        examples=['2021-06-30T09:42:30.168Z'],
    )
    url: Optional[str] = Field(
        None,
        description='The asset file name.',
        examples=[
            'https://cdn.shotstack.io/au/v1/5ca6hu7s9k/2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7.mp4'
        ],
    )


class AssetResponseData(BaseModel):
    attributes: Optional[AssetResponseAttributes] = Field(
        None,
        description='The asset attributes including render id, url, filename, file size, etc...',
    )
    type: Optional[str] = Field(
        None,
        description='The type of resource, in this case it is an assets.',
        examples=['asset'],
    )


class Effect(Enum):
    fadeIn = 'fadeIn'
    fadeOut = 'fadeOut'
    fadeInFadeOut = 'fadeInFadeOut'


class AudioAsset(BaseModel):
    effect: Optional[Effect] = Field(
        None,
        description='The effect to apply to the audio asset <ul>\n  <li>`fadeIn` - fade volume in only</li>\n  <li>`fadeOut` - fade volume out only</li>\n  <li>`fadeInFadeOut` - fade volume in and out</li>\n</ul>',
    )
    src: str = Field(
        ...,
        description='The audio source URL. The URL must be publicly accessible or include credentials.',
        examples=['https://s3-ap-northeast-1.amazonaws.com/my-bucket/sound.mp3'],
    )
    trim: Optional[float] = Field(
        None,
        description='The start trim point of the audio clip, in seconds (defaults to 0). Audio will start from the in trim point. The audio will play until the file ends or the Clip length is reached.',
    )
    type: str = Field(
        ..., description='The type of asset - set to `audio` for audio assets.'
    )
    volume: Optional[float] = Field(
        1,
        description='Set the volume for the audio clip between 0 and 1 where 0 is muted and 1 is full volume (defaults to 1).',
    )


class Effect1(Enum):
    zoomIn = 'zoomIn'
    zoomOut = 'zoomOut'
    slideLeft = 'slideLeft'
    slideRight = 'slideRight'
    slideUp = 'slideUp'
    slideDown = 'slideDown'


class Filter(Enum):
    boost = 'boost'
    contrast = 'contrast'
    darken = 'darken'
    greyscale = 'greyscale'
    lighten = 'lighten'
    muted = 'muted'
    negative = 'negative'


class Fit(Enum):
    cover = 'cover'
    contain = 'contain'
    crop = 'crop'
    none = 'none'


class Position(Enum):
    top = 'top'
    topRight = 'topRight'
    right = 'right'
    bottomRight = 'bottomRight'
    bottom = 'bottom'
    bottomLeft = 'bottomLeft'
    left = 'left'
    topLeft = 'topLeft'
    center = 'center'


class Crop(BaseModel):
    bottom: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None, description='Crop from the bottom of the asset', examples=[0.15]
    )
    left: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None, description='Crop from the left of the asset'
    )
    right: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None, description='Crop from the left of the asset'
    )
    top: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None, description='Crop from the top of the asset', examples=[0.15]
    )


class Disk(Enum):
    local = 'local'
    mount = 'mount'


class Font(BaseModel):
    src: str = Field(
        ...,
        description='The URL of the font file. The URL must be publicly accessible or include credentials.',
        examples=['https://s3-ap-northeast-1.amazonaws.com/my-bucket/open-sans.ttf'],
    )


class HtmlAsset(BaseModel):
    background: Optional[str] = Field(
        'transparent',
        description='Apply a background color behind the HTML bounding box using. Set the text color using hexadecimal  color notation. Transparency is supported by setting the first two characters of the hex string  (opposite to HTML), i.e. #80ffffff will be white with 50% transparency.',
    )
    css: Optional[str] = Field(
        None,
        description='The CSS text string to apply styling to the HTML. See list of  [support CSS properties](https://shotstack.gitbook.io/docs/guides/architecting-an-application/html-support#supported-html-tags).',
        examples=['p { color: #ffffff; } b { color: #ffff00; }'],
    )
    height: Optional[int] = Field(
        None,
        description='Set the width of the HTML asset bounding box in pixels. Text and elements will be masked if they exceed the  height of the bounding box.',
        examples=[200],
    )
    html: str = Field(
        ...,
        description='The HTML text string. See list of [supported HTML tags](https://shotstack.gitbook.io/docs/guides/architecting-an-application/html-support#supported-html-tags).',
        examples=['<p>Hello <b>World</b></p>'],
    )
    position: Optional[Position] = Field(
        'center',
        description='Place the HTML in one of nine predefined positions within the HTML area. <ul>\n  <li>`top` - top (center)</li>\n  <li>`topRight` - top right</li>\n  <li>`right` - right (center)</li>\n  <li>`bottomRight` - bottom right</li>\n  <li>`bottom` - bottom (center)</li>\n  <li>`bottomLeft` - bottom left</li>\n  <li>`left` - left (center)</li>\n  <li>`topLeft` - top left</li>\n  <li>`center` - center</li>\n</ul>',
    )
    type: str = Field(..., description='The type of asset - set to `html` for HTML.')
    width: Optional[int] = Field(
        None,
        description='Set the width of the HTML asset bounding box in pixels. Text will wrap to fill the bounding box.',
        examples=[400],
    )


class ImageAsset(BaseModel):
    crop: Optional[Crop] = None
    src: str = Field(
        ...,
        description='The image source URL. The URL must be publicly accessible or include credentials.',
        examples=['https://s3-ap-northeast-1.amazonaws.com/my-bucket/image.jpg'],
    )
    type: str = Field(..., description='The type of asset - set to `image` for images.')


class LumaAsset(BaseModel):
    src: str = Field(
        ...,
        description='The luma matte source URL. The URL must be publicly accessible or include credentials.',
        examples=['https://s3-ap-northeast-1.amazonaws.com/my-bucket/mask.mp4'],
    )
    trim: Optional[float] = Field(
        None,
        description='The start trim point of the luma matte clip, in seconds (defaults to 0). Videos will start from the in trim point. A luma matte video will play until the file ends or the Clip length is reached.',
    )
    type: str = Field(
        ..., description='The type of asset - set to `luma` for luma mattes.'
    )


class Offset(BaseModel):
    x: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        0,
        description='Offset an asset on the horizontal axis (left or right), range varies from -1 to 1. Positive numbers move the asset right, negative left. For all assets except titles the distance moved is relative to the width  of the viewport - i.e. an X offset of 0.5 will move the asset half the  screen width to the right.',
        examples=[0.1],
    )
    y: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        0,
        description='Offset an asset on the vertical axis (up or down), range varies from -1 to 1. Positive numbers move the asset up, negative down. For all assets except titles the distance moved is relative to the height  of the viewport - i.e. an Y offset of 0.5 will move the asset up half the  screen height.',
        examples=[-0.2],
    )


class AspectRatio(Enum):
    field_16_9 = '16:9'
    field_9_16 = '9:16'
    field_1_1 = '1:1'
    field_4_5 = '4:5'
    field_4_3 = '4:3'


class Format(Enum):
    mp4 = 'mp4'
    gif = 'gif'
    mp3 = 'mp3'
    jpg = 'jpg'
    png = 'png'
    bmp = 'bmp'


class Fps(Enum):
    integer_12 = 12
    integer_15 = 15
    integer_24 = 24
    integer_25 = 25
    integer_30 = 30


class Quality(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Resolution(Enum):
    preview = 'preview'
    mobile = 'mobile'
    sd = 'sd'
    hd = 'hd'
    field_1080 = '1080'


class ScaleTo(Enum):
    preview = 'preview'
    mobile = 'mobile'
    sd = 'sd'
    hd = 'hd'
    field_1080 = '1080'


class Poster(BaseModel):
    capture: float = Field(
        ...,
        description='The point on the timeline in seconds to capture a single frame to use as the poster image.',
        examples=[1],
    )


class QueuedResponseData(BaseModel):
    id: str = Field(
        ...,
        description='The id of the render task in UUID format.',
        examples=['2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7'],
    )
    message: str = Field(
        ...,
        description='Success response message or error details.',
        examples=['Render Successfully Queued'],
    )


class Range(BaseModel):
    length: Optional[confloat(ge=0.0)] = Field(
        None,
        description='The length of the portion of the video or audio to render - i.e. render 6 seconds of the video.',
        examples=[6],
    )
    start: Optional[confloat(ge=0.0)] = Field(
        None,
        description='The point on the timeline, in seconds, to start the render from - i.e. start at second 3.',
        examples=[3],
    )


class Status1(Enum):
    queued = 'queued'
    fetching = 'fetching'
    rendering = 'rendering'
    saving = 'saving'
    done = 'done'
    failed = 'failed'


class ShotstackDestination(BaseModel):
    exclude: Optional[bool] = Field(
        False,
        description='Set to `true` to opt-out from the Shotstack hosting and CDN service. All files must be downloaded within 24 hours of rendering.',
        examples=[False],
    )
    provider: str = Field(
        ...,
        description='The destination to send rendered assets to - set to `shotstack` for Shotstack hosting and CDN.',
        examples=['shotstack'],
    )


class Size(BaseModel):
    height: Optional[conint(ge=0, le=4096)] = Field(
        None,
        description='Set a custom height for the video or image file. Value must be divisible by 2. Maximum video height is 1920px, maximum image height is 4096px.',
        examples=[800],
    )
    width: Optional[conint(ge=0, le=4096)] = Field(
        None,
        description='Set a custom width for the video or image file. Value must be divisible by 2. Maximum video width is 1920px, maximum image width is 4096px.',
        examples=[1200],
    )


class Effect2(Enum):
    fadeIn = 'fadeIn'
    fadeOut = 'fadeOut'
    fadeInFadeOut = 'fadeInFadeOut'


class Soundtrack(BaseModel):
    effect: Optional[Effect2] = Field(
        None,
        description='The effect to apply to the audio file <ul>\n  <li>`fadeIn` - fade volume in only</li>\n  <li>`fadeOut` - fade volume out only</li>\n  <li>`fadeInFadeOut` - fade volume in and out</li>\n</ul>',
    )
    src: str = Field(
        ...,
        description='The URL of the mp3 audio file. The URL must be publicly accessible or include credentials.',
        examples=['https://s3-ap-northeast-1.amazonaws.com/my-bucket/music.mp3'],
    )
    volume: Optional[float] = Field(
        1,
        description='Set the volume for the soundtrack between 0 and 1 where 0 is muted and 1 is full volume (defaults to 1).',
    )


class Thumbnail(BaseModel):
    capture: float = Field(
        ...,
        description='The point on the timeline in seconds to capture a single frame to use as the thumbnail image.',
        examples=[1],
    )
    scale: float = Field(
        ...,
        description='Scale the thumbnail size to a fraction of the viewport size - i.e. setting the scale to 0.5 will scale  the thumbnail to half the size of the viewport.',
        examples=[0.3],
    )


class Size1(Enum):
    xx_small = 'xx-small'
    x_small = 'x-small'
    small = 'small'
    medium = 'medium'
    large = 'large'
    x_large = 'x-large'
    xx_large = 'xx-large'


class Style(Enum):
    minimal = 'minimal'
    blockbuster = 'blockbuster'
    vogue = 'vogue'
    sketchy = 'sketchy'
    skinny = 'skinny'
    chunk = 'chunk'
    chunkLight = 'chunkLight'
    marker = 'marker'
    future = 'future'
    subtitle = 'subtitle'


class TitleAsset(BaseModel):
    background: Optional[str] = Field(
        None,
        description='Apply a background color behind the text. Set the text color using hexadecimal color notation. Transparency is supported by setting the first two characters of the hex string (opposite to HTML),  i.e. #80ffffff will be white with 50% transparency. Omit to use transparent background.',
        examples=['#000000'],
    )
    color: Optional[str] = Field(
        '#ffffff',
        description='Set the text color using hexadecimal color notation. Transparency is supported by setting the first two characters of the hex string (opposite to HTML),  i.e. #80ffffff will be white with  50% transparency.',
    )
    offset: Optional[Offset] = Field(
        None,
        description='Offset the location of the title relative to its position on the screen.',
    )
    position: Optional[Position] = Field(
        'center',
        description='Place the title in one of nine predefined positions of the viewport. <ul>\n  <li>`top` - top (center)</li>\n  <li>`topRight` - top right</li>\n  <li>`right` - right (center)</li>\n  <li>`bottomRight` - bottom right</li>\n  <li>`bottom` - bottom (center)</li>\n  <li>`bottomLeft` - bottom left</li>\n  <li>`left` - left (center)</li>\n  <li>`topLeft` - top left</li>\n  <li>`center` - center</li>\n</ul>',
    )
    size: Optional[Size1] = Field(
        'medium',
        description='Set the relative size of the text using predefined sizes from xx-small to xx-large. <ul>\n  <li>`xx-small`</li>\n  <li>`x-small`</li>\n  <li>`small`</li>\n  <li>`medium`</li>\n  <li>`large`</li>\n  <li>`x-large`</li>\n  <li>`xx-large`</li>\n</ul>',
    )
    style: Optional[Style] = Field(
        None,
        description='Uses a preset to apply font properties and styling to the title. <ul>\n  <li>`minimal`</li>\n  <li>`blockbuster`</li>\n  <li>`vogue`</li>\n  <li>`sketchy`</li>\n  <li>`skinny`</li>\n  <li>`chunk`</li>\n  <li>`chunkLight`</li>\n  <li>`marker`</li>\n  <li>`future`</li>\n  <li>`subtitle`</li>\n</ul>',
    )
    text: str = Field(
        ...,
        description='The title text string - i.e. "My Title".',
        examples=['Hello World'],
    )
    type: str = Field(..., description='The type of asset - set to `title` for titles.')


class In(Enum):
    fade = 'fade'
    fadeSlow = 'fadeSlow'
    fadeFast = 'fadeFast'
    reveal = 'reveal'
    revealSlow = 'revealSlow'
    revealFast = 'revealFast'
    wipeLeft = 'wipeLeft'
    wipeLeftSlow = 'wipeLeftSlow'
    wipeLeftFast = 'wipeLeftFast'
    wipeRight = 'wipeRight'
    wipeRightSlow = 'wipeRightSlow'
    wipeRightFast = 'wipeRightFast'
    slideLeft = 'slideLeft'
    slideLeftSlow = 'slideLeftSlow'
    slideLeftFast = 'slideLeftFast'
    slideRight = 'slideRight'
    slideRightSlow = 'slideRightSlow'
    slideRightFast = 'slideRightFast'
    slideUp = 'slideUp'
    slideUpSlow = 'slideUpSlow'
    slideUpFast = 'slideUpFast'
    slideDown = 'slideDown'
    slideDownSlow = 'slideDownSlow'
    slideDownFast = 'slideDownFast'
    carouselLeft = 'carouselLeft'
    carouselLeftSlow = 'carouselLeftSlow'
    carouselLeftFast = 'carouselLeftFast'
    carouselRight = 'carouselRight'
    carouselRightSlow = 'carouselRightSlow'
    carouselRightFast = 'carouselRightFast'
    carouselUp = 'carouselUp'
    carouselUpSlow = 'carouselUpSlow'
    carouselUpFast = 'carouselUpFast'
    carouselDown = 'carouselDown'
    carouselDownSlow = 'carouselDownSlow'
    carouselDownFast = 'carouselDownFast'
    shuffleTopRight = 'shuffleTopRight'
    shuffleTopRightSlow = 'shuffleTopRightSlow'
    shuffleTopRightFast = 'shuffleTopRightFast'
    shuffleRightTop = 'shuffleRightTop'
    shuffleRightTopSlow = 'shuffleRightTopSlow'
    shuffleRightTopFast = 'shuffleRightTopFast'
    shuffleRightBottom = 'shuffleRightBottom'
    shuffleRightBottomSlow = 'shuffleRightBottomSlow'
    shuffleRightBottomFast = 'shuffleRightBottomFast'
    shuffleBottomRight = 'shuffleBottomRight'
    shuffleBottomRightSlow = 'shuffleBottomRightSlow'
    shuffleBottomRightFast = 'shuffleBottomRightFast'
    shuffleBottomLeft = 'shuffleBottomLeft'
    shuffleBottomLeftSlow = 'shuffleBottomLeftSlow'
    shuffleBottomLeftFast = 'shuffleBottomLeftFast'
    shuffleLeftBottom = 'shuffleLeftBottom'
    shuffleLeftBottomSlow = 'shuffleLeftBottomSlow'
    shuffleLeftBottomFast = 'shuffleLeftBottomFast'
    shuffleLeftTop = 'shuffleLeftTop'
    shuffleLeftTopSlow = 'shuffleLeftTopSlow'
    shuffleLeftTopFast = 'shuffleLeftTopFast'
    shuffleTopLeft = 'shuffleTopLeft'
    shuffleTopLeftSlow = 'shuffleTopLeftSlow'
    shuffleTopLeftFast = 'shuffleTopLeftFast'
    zoom = 'zoom'


class Out(Enum):
    fade = 'fade'
    fadeSlow = 'fadeSlow'
    fadeFast = 'fadeFast'
    reveal = 'reveal'
    revealSlow = 'revealSlow'
    revealFast = 'revealFast'
    wipeLeft = 'wipeLeft'
    wipeLeftSlow = 'wipeLeftSlow'
    wipeLeftFast = 'wipeLeftFast'
    wipeRight = 'wipeRight'
    wipeRightSlow = 'wipeRightSlow'
    wipeRightFast = 'wipeRightFast'
    slideLeft = 'slideLeft'
    slideLeftSlow = 'slideLeftSlow'
    slideLeftFast = 'slideLeftFast'
    slideRight = 'slideRight'
    slideRightSlow = 'slideRightSlow'
    slideRightFast = 'slideRightFast'
    slideUp = 'slideUp'
    slideUpSlow = 'slideUpSlow'
    slideUpFast = 'slideUpFast'
    slideDown = 'slideDown'
    slideDownSlow = 'slideDownSlow'
    slideDownFast = 'slideDownFast'
    carouselLeft = 'carouselLeft'
    carouselLeftSlow = 'carouselLeftSlow'
    carouselLeftFast = 'carouselLeftFast'
    carouselRight = 'carouselRight'
    carouselRightSlow = 'carouselRightSlow'
    carouselRightFast = 'carouselRightFast'
    carouselUp = 'carouselUp'
    carouselUpSlow = 'carouselUpSlow'
    carouselUpFast = 'carouselUpFast'
    carouselDown = 'carouselDown'
    carouselDownSlow = 'carouselDownSlow'
    carouselDownFast = 'carouselDownFast'
    shuffleTopRight = 'shuffleTopRight'
    shuffleTopRightSlow = 'shuffleTopRightSlow'
    shuffleTopRightFast = 'shuffleTopRightFast'
    shuffleRightTop = 'shuffleRightTop'
    shuffleRightTopSlow = 'shuffleRightTopSlow'
    shuffleRightTopFast = 'shuffleRightTopFast'
    shuffleRightBottom = 'shuffleRightBottom'
    shuffleRightBottomSlow = 'shuffleRightBottomSlow'
    shuffleRightBottomFast = 'shuffleRightBottomFast'
    shuffleBottomRight = 'shuffleBottomRight'
    shuffleBottomRightSlow = 'shuffleBottomRightSlow'
    shuffleBottomRightFast = 'shuffleBottomRightFast'
    shuffleBottomLeft = 'shuffleBottomLeft'
    shuffleBottomLeftSlow = 'shuffleBottomLeftSlow'
    shuffleBottomLeftFast = 'shuffleBottomLeftFast'
    shuffleLeftBottom = 'shuffleLeftBottom'
    shuffleLeftBottomSlow = 'shuffleLeftBottomSlow'
    shuffleLeftBottomFast = 'shuffleLeftBottomFast'
    shuffleLeftTop = 'shuffleLeftTop'
    shuffleLeftTopSlow = 'shuffleLeftTopSlow'
    shuffleLeftTopFast = 'shuffleLeftTopFast'
    shuffleTopLeft = 'shuffleTopLeft'
    shuffleTopLeftSlow = 'shuffleTopLeftSlow'
    shuffleTopLeftFast = 'shuffleTopLeftFast'
    zoom = 'zoom'


class Transition(BaseModel):
    in_: Optional[In] = Field(
        None,
        alias='in',
        description='The transition in. Available transitions are:\n  <ul>\n    <li>`fade` - fade in</li>\n    <li>`reveal` - reveal from left to right</li>\n    <li>`wipeLeft` - fade across screen to the left</li>\n    <li>`wipeRight` - fade across screen to the right</li>\n    <li>`slideLeft` - move slightly left and fade in</li>\n    <li>`slideRight` - move slightly right and fade in</li>\n    <li>`slideUp` - move slightly up and fade in</li>\n    <li>`slideDown` - move slightly down and fade in</li>\n    <li>`carouselLeft` - slide in from right to left</li>\n    <li>`carouselRight` - slide in from left to right</li>\n    <li>`carouselUp` - slide in from bottom to top</li>\n    <li>`carouselDown` - slide in from top to bottom</li>\n    <li>`shuffleTopRight` - rotate in from top right</li>\n    <li>`shuffleRightTop` - rotate in from right top</li>\n    <li>`shuffleRightBottom` - rotate in from right bottom</li>\n    <li>`shuffleBottomRight` - rotate in from bottom right</li>\n    <li>`shuffleBottomLeft` - rotate in from bottom left</li>\n    <li>`shuffleLeftBottom` - rotate in from left bottom</li>\n    <li>`shuffleLeftTop` - rotate in from left top</li>\n    <li>`shuffleTopLeft` - rotate in from top left</li>\n    <li>`zoom` - fast zoom in</li>\n  </ul>\nThe transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.',
    )
    out: Optional[Out] = Field(
        None,
        description='The transition out. Available transitions are:\n  <ul>\n    <li>`fade` - fade out</li>\n    <li>`reveal` - reveal from right to left</li>\n    <li>`wipeLeft` - fade across screen to the left</li>\n    <li>`wipeRight` - fade across screen to the right</li>\n    <li>`slideLeft` - move slightly left and fade out</li>\n    <li>`slideRight` - move slightly right and fade out</li>\n    <li>`slideUp` - move slightly up and fade out</li>\n    <li>`slideDown` - move slightly down and fade out</li>\n    <li>`carouselLeft` - slide out from right to left</li>\n    <li>`carouselRight` - slide out from left to right</li>\n    <li>`carouselUp` - slide out from bottom to top</li>\n    <li>`carouselDown` - slide out from top  to bottom</li>\n    <li>`shuffleTopRight` - rotate out from top right</li>\n    <li>`shuffleRightTop` - rotate out from right top</li>\n    <li>`shuffleRightBottom` - rotate out from right bottom</li>\n    <li>`shuffleBottomRight` - rotate out from bottom right</li>\n    <li>`shuffleBottomLeft` - rotate out from bottom left</li>\n    <li>`shuffleLeftBottom` - rotate out from left bottom</li>\n    <li>`shuffleLeftTop` - rotate out from left top</li>\n    <li>`shuffleTopLeft` - rotate out from top left</li>\n    <li>`zoom` - fast zoom out</li>\n  </ul>\nThe transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.',
    )


class VideoAsset(BaseModel):
    crop: Optional[Crop] = None
    src: str = Field(
        ...,
        description='The video source URL. The URL must be publicly accessible or include credentials.',
        examples=['https://s3-ap-northeast-1.amazonaws.com/my-bucket/video.mp4'],
    )
    trim: Optional[float] = Field(
        None,
        description='The start trim point of the video clip, in seconds (defaults to 0). Videos will start from the in trim point. The video will play until the file ends or the Clip length is reached.',
        examples=[2],
    )
    type: str = Field(..., description='The type of asset - set to `video` for videos.')
    volume: Optional[float] = Field(
        None,
        description='Set the volume for the video clip between 0 and 1 where 0 is muted and 1 is full volume (defaults to 0).',
        examples=[1],
    )


class AssetRenderResponse(BaseModel):
    data: Optional[List[AssetResponseData]] = Field(
        None, description='An array of asset resources grouped by render id.'
    )


class AssetResponse(BaseModel):
    data: Optional[AssetResponseData] = Field(None, description='An asset resource.')


class Clip(BaseModel):
    asset: Union[
        VideoAsset, ImageAsset, TitleAsset, HtmlAsset, AudioAsset, LumaAsset
    ] = Field(
        ...,
        description='The type of asset to display for the duration of this Clip. Value must be one of <b>TitleAsset</b>, <b>ImageAsset</b>, <b>VideoAsset</b>, <b>HtmlAsset</b>, <b>AudioAsset</b> or <b>LumaAsset</b>',
    )
    effect: Optional[Effect1] = Field(
        None,
        description='A motion effect to apply to the Clip. <ul>\n  <li>`zoomIn` - slow zoom in</li>\n  <li>`zoomOut` - slow zoom out</li>\n  <li>`slideLeft` - slow slide (pan) left</li>\n  <li>`slideRight` - slow slide (pan) right</li>\n  <li>`slideUp` - slow slide (pan) up</li>\n  <li>`slideDown` - slow slide (pan) down</li>\n</ul>',
    )
    filter: Optional[Filter] = Field(
        None,
        description='A filter effect to apply to the Clip. <ul>\n  <li>`boost` - boost contrast and saturation</li>\n  <li>`contrast` - increase contrast</li>\n  <li>`darken` - darken the scene</li>\n  <li>`greyscale` - remove colour</li>\n  <li>`lighten` - lighten the scene</li>\n  <li>`muted` - reduce saturation and contrast</li>\n  <li>`invert` - invert colors</li>\n</ul>',
        examples=['greyscale'],
    )
    fit: Optional[Fit] = Field(
        'crop',
        description='Set how the asset should be scaled to fit the viewport using one of the following options: \n  <ul>\n    <li>`cover` - stretch the asset to fill the viewport without maintaining the aspect ratio.</li>\n    <li>`contain` - fit the entire asset within the viewport while maintaining the original aspect ratio.</li>\n    <li>`crop` - scale the asset to fill the viewport while maintaining the aspect ratio. The asset will be cropped if it exceeds the bounds of the viewport.</li>\n    <li>`none` - preserves the original asset dimensions and does not apply any scaling.</li>\n  </ul>',
    )
    length: float = Field(
        ...,
        description='The length, in seconds, the Clip should play for.',
        examples=[5],
    )
    offset: Optional[Offset] = Field(
        None,
        description='Offset the location of the asset relative to its position on the viewport. The offset distance is relative to the width of the viewport - for example an x offset of 0.5 will move the asset half the viewport width to the right.',
    )
    opacity: Optional[float] = Field(
        1,
        description='Sets the opacity of the Clip where 1 is opaque and 0 is transparent.',
    )
    position: Optional[Position] = Field(
        'center',
        description='Place the asset in one of nine predefined positions of the viewport. This is most effective for when the asset is scaled and you want to position the element to a specific position. <ul>\n  <li>`top` - top (center)</li>\n  <li>`topRight` - top right</li>\n  <li>`right` - right (center)</li>\n  <li>`bottomRight` - bottom right</li>\n  <li>`bottom` - bottom (center)</li>\n  <li>`bottomLeft` - bottom left</li>\n  <li>`left` - left (center)</li>\n  <li>`topLeft` - top left</li>\n  <li>`center` - center</li>\n</ul>',
    )
    scale: Optional[float] = Field(
        None,
        description='Scale the asset to a fraction of the viewport size - i.e. setting the scale to 0.5 will scale asset to half the size of the viewport. This is useful for picture-in-picture video and  scaling images such as logos and watermarks.',
        examples=[0],
    )
    start: float = Field(
        ...,
        description='The start position of the Clip on the timeline, in seconds.',
        examples=[2],
    )
    transition: Optional[Transition] = None


class Output(BaseModel):
    aspectRatio: Optional[AspectRatio] = Field(
        None,
        description='The aspect ratio (shape) of the video or image. Useful for social media output formats. Options are: <ul>\n  <li>`16:9` - regular landscape/horizontal aspect ratio (default)</li>\n  <li>`9:16` - vertical/portrait aspect ratio</li>\n  <li>`1:1` - square aspect ratio</li>\n  <li>`4:5` - short vertical/portrait aspect ratio</li>\n  <li>`4:3` - legacy TV aspect ratio</li>\n</ul>',
        examples=['16:9'],
    )
    destinations: Optional[List[ShotstackDestination]] = Field(
        None,
        description='A destination is a location where output files can be sent to for serving or hosting. By default all rendered assets are automatically sent to the Shotstack hosting destination. [DestinationShotstack](/#tocs_shotstackdestination) is currently the only option with plans to add more in the future such as S3, YouTube, Vimeo and Mux. If you do not require hosting you can opt-out using the  `exclude` property.',
    )
    format: Format = Field(
        ...,
        description='The output format and type of media file to generate. <ul>\n  <li>`mp4` - mp4 video file</li>\n  <li>`gif` - animated gif</li>\n  <li>`jpg` - jpg image file</li>\n  <li>`png` - png image file</li>\n  <li>`bmp` - bmp image file</li>\n  <li>`mp3` - mp3 audio file (audio only)</li>\n</ul>',
        examples=['mp4'],
    )
    fps: Optional[Fps] = Field(
        25,
        description='Override the default frames per second. Useful for when the source footage is recorded at 30fps, i.e. on  mobile devices. Lower frame rates can be used to add cinematic quality (24fps) or to create smaller file size/faster render times or animated gifs (12 or 15fps). Default is 25fps. <ul>\n  <li>`12` - 12fps</li>\n  <li>`15` - 15fps</li>\n  <li>`24` - 24fps</li>\n  <li>`25` - 25fps</li>\n  <li>`30` - 30fps</li>\n</ul>',
        examples=[25],
    )
    poster: Optional[Poster] = Field(
        None,
        description='Generate a poster image from a specific point on the timeline.',
    )
    quality: Optional[Quality] = Field(
        'medium',
        description='Adjust the output quality of the video, image or audio. Adjusting quality affects  render speed, download speeds and storage requirements due to file size. The default `medium` provides the most optimized choice for all three  factors. <ul>\n  <li>`low` - slightly reduced quality, smaller file size</li>\n  <li>`medium` - optimized quality, render speeds and file size</li>\n  <li>`high` - slightly increased quality, larger file size</li>\n</ul>',
        examples=['medium'],
    )
    range: Optional[Range] = None
    resolution: Optional[Resolution] = Field(
        None,
        description='The output resolution of the video or image. <ul>\n  <li>`preview` - 512px x 288px @ 15fps</li>\n  <li>`mobile` - 640px x 360px @ 25fps</li>\n  <li>`sd` - 1024px x 576px @ 25fps</li>\n  <li>`hd` - 1280px x 720px @ 25fps</li>\n  <li>`1080` - 1920px x 1080px @ 25fps</li>\n</ul>',
        examples=['sd'],
    )
    scaleTo: Optional[ScaleTo] = Field(
        None,
        description='Override the resolution and scale the video or image to render at a different size. When using scaleTo the asset should be edited at the resolution dimensions, i.e. use font sizes that look best at HD, then use scaleTo to output the file at SD and the text will be scaled to the correct size. This is useful if you want to create multiple asset sizes. <ul>\n  <li>`preview` - 512px x 288px @ 15fps</li>\n  <li>`mobile` - 640px x 360px @ 25fps</li>\n  <li>`sd` - 1024px x 576px @25fps</li>\n  <li>`hd` - 1280px x 720px @25fps</li>\n  <li>`1080` - 1920px x 1080px @25fps</li>\n</ul>',
    )
    size: Optional[Size] = None
    thumbnail: Optional[Thumbnail] = Field(
        None,
        description='Generate a thumbnail image from a specific point on the timeline.',
    )


class QueuedResponse(BaseModel):
    message: str = Field(
        ...,
        description='`Created`, `Bad Request` or an error message.',
        examples=['Created'],
    )
    response: QueuedResponseData = Field(
        ..., description='`QueuedResponseData` or an error message.'
    )
    success: bool = Field(
        ..., description='`true` if successfully queued, else `false`.', examples=[True]
    )


class Track(BaseModel):
    clips: List[Clip] = Field(
        ...,
        description='An array of Clips comprising of TitleClip, ImageClip or VideoClip.',
    )


class Timeline(BaseModel):
    background: Optional[str] = Field(
        '#000000',
        description='A hexadecimal value for the timeline background colour. Defaults to #000000 (black).',
    )
    cache: Optional[bool] = Field(
        True,
        description='Disable the caching of ingested source footage and assets. See  [caching](https://shotstack.gitbook.io/docs/guides/architecting-an-application/caching) for more details.',
    )
    fonts: Optional[List[Font]] = Field(
        None,
        description='An array of custom fonts to be downloaded for use by the HTML assets.',
    )
    soundtrack: Optional[Soundtrack] = Field(
        None, description='A music or audio soundtrack file in mp3 format.'
    )
    tracks: List[Track] = Field(
        ...,
        description='A timeline consists of an array of tracks, each track containing clips. Tracks are layered on top of each other in the same order they are added to the array with the top most track layered over the top of those below it. Ensure that a track containing titles is the top most track so that it is displayed above videos and images.',
    )


class Edit(BaseModel):
    callback: Optional[str] = Field(
        None,
        description='An optional webhook callback URL used to receive status notifications when a render completes or fails. See [webhooks](https://shotstack.gitbook.io/docs/guides/architecting-an-application/webhooks) for  more details.',
        examples=['https://my-server.com/callback.php'],
    )
    disk: Optional[Disk] = Field(
        'local',
        description='The disk type to use for storing footage and assets for each render. See [disk types](https://shotstack.gitbook.io/docs/guides/architecting-an-application/disk-types) for more details. <ul>\n  <li>`local` - optimized for high speed rendering with up to 512MB storage</li>\n  <li>`mount` - optimized for larger file sizes and longer videos with 5GB for source footage and 512MB for output render</li>\n</ul>',
    )
    output: Output
    timeline: Timeline


class RenderResponseData(BaseModel):
    created: str = Field(
        ...,
        description='The time the render task was initially queued.',
        examples=['2020-10-30T09:42:29.446Z'],
    )
    data: Edit = Field(..., description='The timeline and output data to be rendered.')
    duration: Optional[float] = Field(
        None, description='The output video or audio length in seconds.', examples=[8.5]
    )
    error: Optional[str] = Field(
        None,
        description='An error message, only displayed if an error occurred.',
        examples=[''],
    )
    id: str = Field(
        ...,
        description='The id of the render task in UUID format.',
        examples=['2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7'],
    )
    owner: str = Field(
        ..., description='The owner id of the render task.', examples=['5ca6hu7s9k']
    )
    plan: Optional[str] = Field(
        None, description='The customer subscription plan.', examples=['basic']
    )
    poster: Optional[str] = Field(
        None,
        description='The URL of the poster image if requested. This will only be available if status is done.',
        examples=[
            'https://shotstack-api-v1-output.s3-ap-southeast-2.amazonaws.com/5ca6hu7s9k/2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7-poster.jpg'
        ],
    )
    renderTime: Optional[float] = Field(
        None,
        description='The time taken to render the asset in milliseconds.',
        examples=[9433.44],
    )
    status: Status1 = Field(
        ...,
        description='The status of the render task. <ul>\n  <li>`queued` - render is queued waiting to be rendered</li>\n  <li>`fetching` - assets are being fetched</li>\n  <li>`rendering` - the asset is being rendered</li>\n  <li>`saving` - the final asset is being saved to storage</li>\n  <li>`done` - the asset is ready to be downloaded</li>\n  <li>`failed` - there was an error rendering the asset</li>\n</ul>',
        examples=['done'],
    )
    thumbnail: Optional[str] = Field(
        None,
        description='The URL of the thumbnail image if requested. This will only be available if status is done.',
        examples=[
            'https://shotstack-api-v1-output.s3-ap-southeast-2.amazonaws.com/5ca6hu7s9k/2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7-thumb.jpg'
        ],
    )
    updated: str = Field(
        ...,
        description='The time the render status was last updated.',
        examples=['2020-10-30T09:42:39.168Z'],
    )
    url: Optional[str] = Field(
        None,
        description='The URL of the final asset. This will only be available if status is done. This is a temporary URL and will be deleted after 24 hours. By default all assets are copied to the Shotstack hosting and CDN destination.',
        examples=[
            'https://shotstack-api-v1-output.s3-ap-southeast-2.amazonaws.com/5ca6hu7s9k/2abd5c11-0f3d-4c6d-ba20-235fc9b8e8b7.mp4'
        ],
    )


class RenderResponse(BaseModel):
    message: str = Field(..., description='`OK` or an error message.', examples=['OK'])
    response: RenderResponseData = Field(
        ..., description='`RenderResponse` or an error message.'
    )
    success: bool = Field(
        ..., description='`true` if status available, else `false`.', examples=[True]
    )
